const PSYCHOLOGY_DATA = [
    {
        id: 1,
        titleEn: "THE ESSENCE",
        titleKo: "심리학의 본질",
        items: [
            { type: "field", term: "심리학", desc: "인간의 정신과정과 행동을 과학적으로 연구하는 학문" },
            { type: "scholar", term: "분트(Wundt)", desc: "1879년 최초의 심리학 실험실을 개설하여 실험심리학의 탄생을 알린 인물" },
            { type: "theory", term: "내성법", desc: "실험이라는 통제된 조건 속에서 자신의 의식 경험을 스스로 분석하는 방법" },
            { type: "theory", term: "심적 요소", desc: "여러 개의 요소로 분석한 의식의 최소 단위" },
            { type: "theory", term: "행동주의", desc: "심리학의 목적을 인간 및 동물의 행동을 예측하고 제어하는 데 둔 관점" },
            { type: "theory", term: "형태주의", desc: "인간의 정신은 요소의 집합이 아닌 전체성을 가진 구조라고 주장하는 학파" },
            { type: "field", term: "기초심리학", desc: "관찰·실험·조사로 일반 법칙을 탐구하는 분야" },
            { type: "field", term: "응용심리학", desc: "현실 문제의 해결과 개선에 심리학적 원리를 적용하는 분야" },
            { type: "method", term: "심리학 연구방법", desc: "실험법, 관찰법, 조사법, 임상법 등이 포함되는 연구 방식" },
            { type: "variable", term: "독립변인", desc: "실험 결과에 영향을 주기 위해 실험자가 직접 조작하는 변인" },
            { type: "variable", term: "종속변인", desc: "독립변인의 조작에 따라 변화하며 측정되는 결과 변인" },
            { type: "variable", term: "통제변인", desc: "실험 결과에 영향을 미치지 않도록 일정하게 유지하는 변인" }
        ]
    },
    {
        id: 2,
        titleEn: "BIOLOGICAL BASIS",
        titleKo: "행동의 생리적 기초",
        items: [
            { type: "structure", term: "신경세포", desc: "신경계를 구성하는 기본단위로 정보전달과 정보처리 기능을 담당함" },
            { type: "structure", term: "시냅스", desc: "신경세포 상호 간의 접합부위" },
            { type: "structure", term: "신경전달물질", desc: "시냅스에서 신경세포 간의 정보전달을 중개하는 물질" },
            { type: "system", term: "중추 신경", desc: "뇌와 척수로 구성된 신경계의 중심축" },
            { type: "system", term: "말초 신경", desc: "체성 신경(운동·감각)과 자율 신경(교감·부교감)으로 구성된 신경계" },
            { type: "brain", term: "좌반구", desc: "대뇌에서 이성적인 사고를 담당하는 중추" },
            { type: "brain", term: "우반구", desc: "대뇌에서 창조적 활동 및 예술적 능력에 관여하는 중추" },
            { type: "brain", term: "신 피질", desc: "언어, 판단, 창조 등의 고도의 정신기능을 담당하는 부위" },
            { type: "brain", term: "구 피질", desc: "정동행동, 식욕, 성욕, 기억 등을 담당하는 부위" },
            { type: "brain", term: "대뇌 변연계", desc: "본능행동, 정동, 자율 신경을 담당하는 계통" },
            { type: "brain", term: "편도체", desc: "외부 자극에 대하여 유쾌, 불쾌, 불안 등의 본능적 반응을 일으키는 부위" },
            { type: "brain", term: "해마", desc: "기억의 정리와 관리를 담당하는 부위" },
            { type: "brain", term: "뇌량", desc: "뇌의 좌반구와 우반구를 연결하여 정보를 교환하게 함" },
            { type: "lobe", term: "전두엽", desc: "대뇌피질에서 사고, 판단, 계산 등을 담당하는 부위" },
            { type: "lobe", term: "두정엽", desc: "대뇌피질에서 신체의 입체감각 등을 담당하는 부위" },
            { type: "lobe", term: "측두엽", desc: "대뇌피질에서 청각, 언어, 기억 등을 담당하는 부위" },
            { type: "lobe", term: "후두엽", desc: "대뇌피질에서 시각 정보의 처리를 담당하는 부위" },
            { type: "brain-sub", term: "소뇌", desc: "신체운동의 균형을 조절하는 뇌 부위" },
            { type: "brain-sub", term: "시상", desc: "중뇌, 뇌교, 연수로부터 온 정보를 대뇌로 전달하는 중계소" },
            { type: "brain-sub", term: "시상하부", desc: "섭식, 음수, 체온 조절 등 생명 유지에 가장 중요한 역할을 담당" },
            { type: "spinal", term: "척수반사", desc: "뇌를 거치지 않고 척수만의 판단으로 신속히 처리하는 반응(예: 뜨거운 것 피하기)" },
            { type: "autonomic", term: "교감 신경", desc: "활동 시, 긴장과 스트레스를 느낄 때 기능하는 자율 신경" },
            { type: "autonomic", term: "부교감 신경", desc: "휴식 시, 수면을 취할 때 기능하는 자율 신경" },
            { type: "condition", term: "분리 뇌", desc: "좌뇌와 우뇌를 연결하는 뇌량이 절단되어 정보 공유가 불가능한 상태" },
            { type: "condition", term: "브로카 실어증", desc: "말은 이해하나 표현이 매끄럽지 못한 표현적 실어증" },
            { type: "condition", term: "베르니케 실어증", desc: "발화는 유창하나 이해 능력이 손상된 수용적 실어증" }
        ]
    },
    {
        id: 3,
        titleEn: "PSYCHOLOGICAL DEVELOPMENT",
        titleKo: "심리적 발달",
        items: [
            { type: "dev-def", term: "발달", desc: "출생에서 사망에 이르는 전 생애에 걸친 신체적·정신적 변화 과정" },
            { type: "dev-method", term: "종단적 방법", desc: "둘 이상의 시점에서 동일한 분석 단위를 장기간에 걸쳐 추적하는 방법" },
            { type: "dev-method", term: "횡단적 방법", desc: "어느 한 시점에서 다수의 분석 단위에 대한 자료를 수집하는 방법" },
            { type: "dev-principle", term: "두미법칙", desc: "발달이 머리(위)에서 발(아래) 방향으로 진행된다는 원리" },
            { type: "dev-principle", term: "중심말단법칙", desc: "발달이 중추에서 말초 방향으로 진행된다는 원리" },
            { type: "piaget", term: "감각운동기", desc: "0~2세. 현재 세계만 인식하며 자신과 외부대상을 구분하지 못함" },
            { type: "piaget", term: "전조작기", desc: "2~7세. 직관적 사고가 특징이며 대상영속성을 습득함" },
            { type: "piaget", term: "구체적 조작기", desc: "7~12세. 분류·서열화·보존개념이 형성되며 논리적 사고가 가능함" },
            { type: "piaget", term: "형식적 조작기", desc: "12세 이상. 추상적 사고, 연역적 사고, 가설 설정이 가능함" },
            { type: "kohlberg", term: "전인습적 수준", desc: "4~10세. 타율적 도덕성 및 욕구충족 수단으로서의 도덕성 단계" },
            { type: "kohlberg", term: "인습적 수준", desc: "10~13세. 대인관계의 조화와 법·질서 준수를 중시하는 단계" },
            { type: "kohlberg", term: "후인습적 수준", desc: "13세 이상. 사회계약정신과 보편적 도덕원리를 지향하는 단계" },
            { type: "freud", term: "구강기", desc: "0~1세. 리비도가 구강에 집중되는 시기" },
            { type: "freud", term: "항문기", desc: "1~3세. 배변훈련을 통한 사회화의 기대에 직면하는 시기" },
            { type: "freud", term: "남근기", desc: "3~6세. 리비도가 성기에 집중되며 초자아가 성립되는 시기" },
            { type: "freud", term: "잠복기", desc: "6~12세. 성적 충동이 잠재되며 리비도의 대상이 동성 친구인 시기" },
            { type: "freud", term: "생식기", desc: "12세 이후. 사춘기와 2차 성징이 나타나며 이성 친구에 관심을 가짐" },
            { type: "erikson", term: "신뢰감 대 불신감", desc: "출생~18개월. 유아기에 형성되며 주요 덕목은 희망임" },
            { type: "erikson", term: "자율성 대 수치심", desc: "18개월~3세. 초기 아동기에 형성되며 주요 덕목은 의지력임" },
            { type: "erikson", term: "주도성 대 죄의식", desc: "3~5세. 학령전기(유희기)에 형성되며 주요 덕목은 목적의식임" },
            { type: "erikson", term: "근면성 대 열등감", desc: "5~12세. 학령기에 형성되며 주요 덕목은 능력감임" },
            { type: "erikson", term: "자아정체감 대 혼란", desc: "12~20세. 청소년기에 형성되며 주요 덕목은 성실성임" },
            { type: "erikson", term: "친밀감 대 고립감", desc: "20~24세. 성인 초기에 형성되며 주요 덕목은 사랑임" },
            { type: "erikson", term: "생산성 대 침체", desc: "24~65세. 성인기에 형성되며 주요 덕목은 배려임" },
            { type: "erikson", term: "자아통합 대 절망", desc: "65세 이후. 노년기에 형성되며 주요 덕목은 지혜임" }
        ]
    },
    {
        id: 4,
        titleEn: "MOTIVATION AND EMOTION",
        titleKo: "동기와 정서",
        items: [
            { type: "motive-def", term: "동기", desc: "일정한 방향으로 행동을 일으키고 지속시키는 과정이자 행동의 원동력" },
            { type: "motive-def", term: "일차적 동기", desc: "생리적·기본적 욕구와 관련된 생존을 위한 동기" },
            { type: "motive-def", term: "이차적 동기", desc: "학습이나 사회적 상호작용을 통해 습득되는 사회적 동기" },
            { type: "maslow", term: "생리적 욕구", desc: "매슬로우 욕구 5단계 중 최하위 단계인 의식주 등 기본적 욕구" },
            { type: "maslow", term: "안전에 대한 욕구", desc: "위험, 위협, 박탈로부터 자신을 보호하려는 욕구" },
            { type: "maslow", term: "애정과 소속의 욕구", desc: "타인과 친밀한 관계를 맺고 집단에 소속되고자 하는 사회적 욕구" },
            { type: "maslow", term: "존경의 욕구", desc: "타인으로부터 인정받고 집단 내에서 명성을 얻고자 하는 욕구" },
            { type: "maslow", term: "자아실현의 욕구", desc: "매슬로우 욕구 5단계 중 최상위 단계로 잠재력을 완전히 발휘하려는 욕구" },
            { type: "bio-motive", term: "항상성(Homeostasis)", desc: "신체의 상태를 생존에 최적인 일정한 상태로 유지하려는 기능" },
            { type: "bio-motive", term: "추동(Drive)", desc: "배고픔, 목마름 등 생리적 결핍 상태를 해소하기 위해 반응하는 원동력" },
            { type: "psych-motive", term: "외재적 동기", desc: "보상, 칭찬, 벌과 같은 외부 요인에 의해 발생하는 동기부여" },
            { type: "psych-motive", term: "내재적 동기", desc: "자기결정이나 지적 호기심 등 자신의 내면으로부터 발생하는 동기" },
            { type: "social-motive", term: "친화동기", desc: "타인과 우호적인 관계를 형성하고 유지하고자 하는 사회적 동기" },
            { type: "social-motive", term: "달성동기", desc: "목표를 세우고 이를 높은 수준으로 완수하고자 하는 사회적 동기" },
            { type: "emotion-def", term: "정서", desc: "기쁨, 슬픔, 분노 등 외부 자극에 의한 일시적이고 급격한 감정 변화" },
            { type: "emotion-theory", term: "James-Lange 이론", desc: "신체적 변화가 정서 경험의 원인이 된다는 이론 (말초기원설)" },
            { type: "emotion-theory", term: "Cannon-Bard 이론", desc: "신체 반응과 정서 경험이 뇌의 중추에서 동시에 일어난다는 이론" },
            { type: "emotion-theory", term: "Schachter의 2요인설", desc: "정서는 신체 반응에 대한 인지적 해석의 결과라는 이론" },
            { type: "emotion-theory", term: "Plutchik의 이론", desc: "8가지 기본 정서가 섞여 새로운 정서가 만들어진다는 이론" }
        ]
    },
    {
        id: 5,
        titleEn: "SENSATION & PERCEPTION",
        titleKo: "감각과 지각",
        items: [
            { type: "sens-def", term: "감각", desc: "감각기관에 대한 자극으로 일어나는 주관적 경험" },
            { type: "sens-meas", term: "절대역", desc: "외부의 자극을 감지할 수 있는 최소한의 물리량" },
            { type: "sens-meas", term: "차이역", desc: "자극의 강도 차이를 감지할 수 있는 최소치(최소가치 차이)" },
            { type: "sens-law", term: "베버의 법칙", desc: "차이역은 처음 자극의 크기에 비례하여 변화함 $$\\frac{\\Delta I}{I} = K$$" },
            { type: "sens-law", term: "페히너의 법칙", desc: "감각의 크기는 자극 강도의 대수에 비례함 $$S = k \\log I$$" },
            { type: "sens-def", term: "가시광선", desc: "눈으로 지각되는 전자파의 영역" },
            { type: "color-theory", term: "삼원색 이론", desc: "색의 지각은 삼원색의 각 파장에 대한 반응의 조합이라는 이론" },
            { type: "color-theory", term: "반대색설", desc: "빨강-초록, 흰-검, 파랑-노랑의 대립 쌍을 통해 색을 인식한다는 이론" },
            { type: "vision-path", term: "복측 경로(What)", desc: "V1에서 측두엽으로 이어지며 사물의 형태를 인지하는 경로" },
            { type: "vision-path", term: "배측 경로(Where)", desc: "V1에서 두정엽으로 이어지며 사물의 운동지각을 담당하는 경로" },
            { type: "sens-def", term: "음의 3요소", desc: "소리의 특징을 결정하는 음의 크기, 음의 고저, 음색" },
            { type: "sens-def", term: "주파수", desc: "진폭이 1초 동안 반복되는 횟수" },
            { type: "sens-def", term: "지각", desc: "감각 수용기를 통해 외부 사물이나 사상의 상태와 변화를 파악하는 것" },
            { type: "gestalt", term: "체제화 원리", desc: "근접, 유사, 폐쇄, 연속성 등의 원리로 대상을 그룹화하여 지각하는 방식" },
            { type: "constancy", term: "지각 항상성", desc: "근자극이 변해도 대상의 성질(크기, 모양, 밝기 등)을 일정하게 유지하려는 작용" },
            { type: "depth-cue", term: "단안단서", desc: "한 눈으로 깊이를 지각하는 측면(중첩, 선형조망, 결의 밀도 등)" },
            { type: "depth-cue", term: "양안시차", desc: "두 눈이 떨어진 거리만큼 다른 시야를 갖게 되어 생기는 입체 지각" },
            { type: "motion", term: "실제운동", desc: "대상이 물리적으로 움직일 때 생기는 현상" },
            { type: "motion", term: "가현운동", desc: "물리적 운동이 없어도 특정 조건에서 지각되는 운동" },
            { type: "motion", term: "유인운동", desc: "두 대상 간의 거리가 변화하면서 지각되는 운동" },
            { type: "attention", term: "선택적 주의", desc: "여러 정보 속에서 특정 정보에만 의식을 집중하는 현상(칵테일파티 효과)" }
        ]
    },
    {
        id: 6,
        titleEn: "LEARNING & MEMORY",
        titleKo: "학습과 기억",
        items: [
            { type: "learn-def", term: "학습", desc: "경험에 의해 나타나는 비교적 영속적인 행동의 변화" },
            { type: "classical", term: "무조건 자극(US)", desc: "학습 없이도 자연스럽게 무조건 반응(UR)을 일으키는 자극" },
            { type: "classical", term: "무조건 반응(UR)", desc: "무조건 자극(US)에 의해 나타나는 생득적이고 자동적인 반응" },
            { type: "classical", term: "조건 자극(CS)", desc: "무조건 자극과 연합되어 나중에는 단독으로 반응을 일으키는 중성 자극" },
            { type: "classical", term: "조건 반응(CR)", desc: "학습을 통해 조건 자극(CS)만으로도 나타나게 된 반응" },
            { type: "classical", term: "자발적 회복", desc: "소거 이후 추가 훈련 없이도 학습된 행동이 다시 나타나는 현상" },
            { type: "classical", term: "자극일반화", desc: "조건화 이후 원래의 조건 자극과 유사한 자극에도 반응을 보이는 현상" },
            { type: "classical", term: "고차조건 형성", desc: "학습된 조건 자극을 다른 중성 자극과 연합시켜 새로운 조건 자극을 만드는 과정" },
            { type: "operant", term: "강화", desc: "어떠한 자극 조건에서 특정 반응이 나타나는 빈도를 높이는 과정" },
            { type: "operant", term: "강화물", desc: "반응의 빈도를 높이는 데 사용되는 자극물" },
            { type: "operant", term: "소거", desc: "바람직하지 않은 행동을 감소시키기 위해 자극조건의 제시를 중지하는 것" },
            { type: "operant", term: "벌", desc: "행동을 감소시키기 위해 불쾌한 자극을 가하는 것" },
            { type: "operant", term: "정적 강화", desc: "유쾌 자극 제시 → 빈도 증가" },
            { type: "operant", term: "부적 강화", desc: "불쾌 자극 소거 → 빈도 증가" },
            { type: "operant", term: "정적 처벌", desc: "불쾌 자극 제시 → 빈도 감소" },
            { type: "operant", term: "부적 처벌", desc: "유쾌 자극 소거 → 빈도 감소" },
            { type: "schedule", term: "고정간격계획(FI)", desc: "일정한 시간이 지난 후 처음 행동이 있을 때 강화물을 부여" },
            { type: "schedule", term: "가변간격계획(VI)", desc: "일정하지 않은 시간이 지난 후 처음 행동에 강화물을 부여" },
            { type: "schedule", term: "고정비율계획(FR)", desc: "정해진 횟수만큼 행동했을 때 강화물을 부여" },
            { type: "schedule", term: "가변비율계획(VR)", desc: "일정하지 않은 몇 번의 행동이 있을 때 강화물을 부여" },
            { type: "memory-proc", term: "부호화(Encoding)", desc: "외부 정보를 기억 시스템에 맞게 변환하는 과정" },
            { type: "memory-proc", term: "응고화(Storage)", desc: "정보를 일정한 기간 동안 저장하고 보존하는 과정" },
            { type: "memory-proc", term: "인출(Retrieval)", desc: "저장된 정보를 다시 끄집어내는 과정" },
            { type: "memory-type", term: "감각기억", desc: "감각기관을 통해 들어온 정보를 아주 짧은 시간 동안 저장" },
            { type: "memory-type", term: "단기기억", desc: "장기기억에 앞서 정보를 일시적으로 보관" },
            { type: "memory-type", term: "장기기억", desc: "정보를 무제한·영구적으로 저장" },
            { type: "ltm-cat", term: "일화기억", desc: "개인의 자전적 기억" },
            { type: "ltm-cat", term: "의미기억", desc: "일반적인 지식·정보" },
            { type: "ltm-cat", term: "절차기억", desc: "몸으로 익힌 기억으로 언어로 표현할 수 없음" },
            { type: "forgetting", term: "쇠퇴", desc: "시간의 흐름에 따라 사용되지 않는 정보의 망각" },
            { type: "forgetting", term: "역행간섭", desc: "이후에 학습한 것이 이전에 학습한 것을 간섭" },
            { type: "forgetting", term: "순행간섭", desc: "먼저 학습한 것이 나중에 학습한 것을 간섭" }
        ]
    },
    {
        id: 7,
        titleEn: "LANGUAGE & THOUGHT",
        titleKo: "언어와 사고",
        items: [
            { type: "representation", term: "명제 표상", desc: "대상에 의미를 부여하여 언어기호로 기술하는 추상적인 표상" },
            { type: "concept", term: "개념", desc: "개개의 대상에 공통된 속성을 추상화·범주화하는 심적 표상" },
            { type: "concept", term: "개념형성", desc: "대상을 추상화하여 어떤 범주에 속하는 것으로 일반화하는 과정" },
            { type: "concept", term: "범주화", desc: "유사한 속성을 가진 대상들을 어느 기준에 따라 하나로 묶는 것" },
            { type: "theory-lang", term: "원형이론", desc: "범주 내의 전형적인 예(원형)와 그것의 유사성으로 대상을 분류하는 이론" },
            { type: "theory-lang", term: "가족 유사성", desc: "범주 구성원들이 모든 특성을 공유하지는 않지만 겹치는 특성을 갖는다는 이론" },
            { type: "lang-theory", term: "생득이론(Chomsky)", desc: "인간은 선천적인 언어습득장치(LAD)를 가지고 태어난다는 이론" },
            { type: "lang-theory", term: "학습이론(Skinner)", desc: "언어습득은 강화와 소거 등 조건형성 원리에 의해 이루어진다는 이론" },
            { type: "lang-dev", term: "옹알이기", desc: "생후 1~8개월경 나타나는 의미 없는 발성 단계" },
            { type: "lang-dev", term: "한 단어 시기", desc: "생후 1년경 한 단어로 다양한 내용을 전달하는 시기(과잉확대·축소 발생)" },
            { type: "lang-dev", term: "두 단어 시기", desc: "18개월 무렵 전보식 문장(조사 등이 탈락)을 구사" },
            { type: "lang-dev", term: "어휘 수의 변화", desc: "12개월 이후 문장을 구성하는 단어 수와 종류가 비약적으로 증가" },
            { type: "lang-dev", term: "과잉일반화", desc: "익힌 문법 규칙을 불규칙한 상황에도 무리하게 적용하는 현상" },
            { type: "problem-solving", term: "잘 정의된 문제", desc: "초기·목표 상태와 제어 조건 등 문제 해결 과정이 명확히 포함된 문제" },
            { type: "problem-solving", term: "추론", desc: "기존 정보를 바탕으로 새로운 결론을 도출하는 사고 과정" },
            { type: "problem-solving", term: "유추", desc: "과거에 경험한 유사 사례를 활용하여 새로운 문제를 추론하는 방식" },
            { type: "problem-solving", term: "통찰", desc: "정보의 통합을 통해 시행착오 없이 비약적으로 문제를 해결하는 과정" },
            { type: "fixation", term: "기능적 고착", desc: "사물의 습관적 용도에만 갇혀 새로운 잠재적 기능을 활용하지 못하는 경향" }
        ]
    },
    {
        id: 8,
        titleEn: "MENTAL ABILITY",
        titleKo: "정신능력과 측정",
        items: [
            { type: "metric", term: "신뢰도", desc: "측정 결과의 안정성 및 일관성(검사-재검사, 동형검사, 반분 신뢰도 등)" },
            { type: "metric", term: "타당도", desc: "측정 도구가 측정하고자 의도한 바를 얼마나 잘 반영하는가의 정도" },
            { type: "test-sb", term: "비율 IQ", desc: "스탠포드-비네 검사에서 사용하는 지능지수 개념 $$IQ = \\frac{MA}{CA} \\times 100$$" },
            { type: "test-w", term: "편차 IQ", desc: "동일 연령 집단의 평균치에 대한 상대적인 위치로 지능을 측정하는 방식" },
            { type: "test-w", term: "웩슬러 지능검사", desc: "언어성 및 동작성 소검사로 구성되며 연령별(WPPSI, WISC, WAIS)로 구분됨" },
            { type: "intel-def", term: "지능", desc: "환경 적응 능력, 과제 대처 능력 및 학습 능력을 포함하는 총체적 능력" },
            { type: "intel-theory", term: "Spearman의 2요인설", desc: "지능은 일반요인(G)과 특수요인(S)으로 구성된다는 이론" },
            { type: "intel-theory", term: "서스톤의 다요인설", desc: "지능은 언어, 수리 등 7가지 기본정신능력으로 구성된다는 이론" },
            { type: "guilford", term: "길포드의 입체모형설", desc: "내용, 조작, 결과의 세 차원이 조합되어 180개의 지능 요소를 이룬다는 이론" },
            { type: "modern-intel", term: "유동성 지능", desc: "유전적·생리적 영향이 크며 새로운 상황에서 발휘되는 지능(카텔과 혼)" },
            { type: "modern-intel", term: "결정성 지능", desc: "환경·경험·교육을 통해 습득된 지식과 문화적 능력을 포함하는 지능" },
            { type: "modern-intel", term: "가드너의 다중지능이론", desc: "인간의 지능은 서로 독립적인 다수의 능력으로 구성됨" },
            { type: "modern-intel", term: "스턴버그의 삼원지능이론", desc: "분석적(성분적), 창의적(경험적), 실용적(상황적) 지능으로 구성됨" },
            { type: "intel-def", term: "유전계수", desc: "개인 간의 지능 차이에서 유전적인 요소가 차지하는 비율" }
        ]
    },
    {
        id: 9,
        titleEn: "PERSONALITY",
        titleKo: "성격과 측정",
        items: [
            { type: "trait-theory", term: "올포트(Allport)", desc: "성격 특성을 주특성, 중심특성, 이차적 특성으로 구분" },
            { type: "trait-theory", term: "카텔(Cattell)", desc: "표면특성과 원천특성을 구분" },
            { type: "trait-theory", term: "아이젠크(Eysenck)", desc: "성격의 차원을 외향-내향, 신경증적 경향으로 분석" },
            { type: "psycho-level", term: "의식", desc: "감각과 경험으로 인식할 수 있는 영역" },
            { type: "psycho-level", term: "전의식", desc: "필요할 때 의식화할 수 있는 영역" },
            { type: "psycho-level", term: "무의식", desc: "자각하지 못하는 사고와 감정의 심층 영역" },
            { type: "psycho-struct", term: "원초아(Id)", desc: "쾌락의 원리에 지배되는 본능적 영역" },
            { type: "psycho-struct", term: "자아(Ego)", desc: "현실 원리에 따라 원초아를 통제하는 영역" },
            { type: "psycho-struct", term: "초자아(Superego)", desc: "도덕적 원리와 양심에 따라 행동하게 하는 영역" },
            { type: "social-learn", term: "관찰학습(모델링)", desc: "타인의 행동과 그 결과를 관찰함으로써 행동의 변화가 일어나는 학습" },
            { type: "social-learn", term: "대리강화", desc: "모델이 강화받는 것을 관찰함으로써 학습자가 간접적으로 강화되는 현상" },
            { type: "humanistic", term: "자기개념", desc: "자기 자신에 대해 가지는 지식이나 이미지" },
            { type: "humanistic", term: "자기일치", desc: "자기개념과 실제 경험이 일치하는 상태" },
            { type: "humanistic", term: "자기실현", desc: "자아를 초월하여 자율성을 향해 심리적으로 성숙해가는 과정" },
            { type: "big-five", term: "신경증(N)", desc: "불안, 우울증 등 정서적 불안정성을 측정하는 요인" },
            { type: "big-five", term: "개방성(O)", desc: "상상력, 호기심 등 새로운 경험에 대한 수용성 요인" },
            { type: "big-five", term: "성실성(C)", desc: "근면, 성취지향 등 목표 지향적 행동을 측정하는 요인" },
            { type: "big-five", term: "순응성(A)", desc: "온화함, 신뢰 등 타인과의 협력적 태도를 측정하는 요인" },
            { type: "big-five", term: "외향성(E)", desc: "사교성, 활동성 등 타인과의 상호작용 의지를 측정하는 요인" },
            { type: "pers-test", term: "자기보고법", desc: "질문항목에 대해 피험자가 스스로 회답(예: MMPI)" },
            { type: "pers-test", term: "투사법", desc: "비구조화된 자극에 정서가 투영되도록 함(예: 로샤검사)" }
        ]
    },
    {
        id: 10,
        titleEn: "ADAPTATION & ABNORMALITY",
        titleKo: "적응과 이상행동",
        items: [
            { type: "stress", term: "욕구좌절(Frustration)", desc: "욕구충족 지연으로 인한 불쾌한 긴장상태" },
            { type: "stress", term: "갈등(Conflict)", desc: "동시에 만족시킬 수 없는 욕구 사이의 선택 상황" },
            { type: "conflict", term: "접근-접근형", desc: "둘 다 매력적인 선택지 사이의 갈등" },
            { type: "conflict", term: "회피-회피형", desc: "둘 다 바람직하지 않은 선택지 사이의 갈등" },
            { type: "conflict", term: "접근-회피형", desc: "매력과 혐오 요소를 동시에 가진 목표에 대한 갈등" },
            { type: "defense", term: "방어기제", desc: "불쾌한 감정을 대처 수준으로 변용하는 심리 작용" },
            { type: "defense", term: "억압", desc: "용납할 수 없는 것들을 의식 밖으로 몰아냄" },
            { type: "defense", term: "부정", desc: "의식하고 싶지 않은 것들을 부정함" },
            { type: "defense", term: "합리화", desc: "핑계를 대거나 다른 것에 책임을 전가함" },
            { type: "defense", term: "투사", desc: "자신의 결점이나 감정을 타인에게 돌리는 것" },
            { type: "defense", term: "반응형성", desc: "실제 감정과 정반대되는 행동을 함" },
            { type: "defense", term: "승화", desc: "사회적으로 허용되는 형태로 욕구를 표출함" },
            { type: "stress", term: "외인성/내인성/심인성", desc: "심리적 장애의 전통적 분류 기준" },
            { type: "disorder-diag", term: "DSM-5", desc: "미국정신의학회(APA)의 정신질환 진단 및 통계 편람" },
            { type: "disorder-diag", term: "ICD", desc: "WHO의 국제질병분류" },
            { type: "psychosis", term: "정신분열증", desc: "피해망상, 대인기피 등을 특징으로 하는 사고 장애" },
            { type: "psychosis", term: "조울증", desc: "조증과 우울증이 교대로 나타나는 기분 장애" },
            { type: "neurotic", term: "불안장애", desc: "공황장애, 강박장애 등을 포함하는 신경증 장애" },
            { type: "neurotic", term: "PTSD", desc: "외상 후 스트레스 장애" },
            { type: "pers-disorder", term: "편집성 성격장애", desc: "타인에 대한 강한 불신과 의심을 특징으로 함" },
            { type: "pers-disorder", term: "반사회적 성격장애", desc: "타인의 권리를 무시하고 규범을 위반함" },
            { type: "pers-disorder", term: "경계선 성격장애", desc: "정서와 대인관계가 매우 불안정한 상태" }
        ]
    },
    {
        id: 11,
        titleEn: "SOCIAL BEHAVIOR",
        titleKo: "사회적 행동",
        items: [
            { type: "attitude", term: "태도", desc: "특정 대상에 대한 감정적 경향" },
            { type: "attitude", term: "인지적 요소", desc: "경험과 학습을 통해 얻은 지식·신념" },
            { type: "attitude", term: "감정적 요소", desc: "대상에 대한 정서적인 반응" },
            { type: "attitude", term: "행동적 요소", desc: "대상에 대해 특정 행동을 하려는 경향" },
            { type: "attitude-theory", term: "인지부조화이론", desc: "모순된 인지요소 사이의 부조화를 해소하려는 경향" },
            { type: "persuasion", term: "신빙성(슬리퍼 효과)", desc: "정보원의 신뢰도가 시간이 지나며 설득에 미치는 영향" },
            { type: "persuasion", term: "문간에 발 들여놓기", desc: "작은 승낙을 통해 나중에 큰 승낙을 얻는 기법" },
            { type: "persuasion", term: "면전에서 문 닫기", desc: "큰 요청 거절 후 작은 요청으로 승낙을 얻는 기법" },
            { type: "social-influence", term: "동조현상", desc: "집단이 제시하는 표준이나 기대에 따르는 행동" },
            { type: "impression", term: "후광효과(Halo)", desc: "긍정적 특징이 전체 평가에 영향을 주는 것" },
            { type: "impression", term: "피그말리온 효과", desc: "누군가에 대한 기대가 실제 성취로 이어지는 것" },
            { type: "impression", term: "부정적 편향", desc: "부정적인 정보가 판단을 크게 좌우하는 경향" },
            { type: "attribution", term: "내적 귀인", desc: "행위자의 능력·성격에 원인을 귀속" },
            { type: "attribution", term: "외적 귀인", desc: "상황·환경에 원인을 귀속" },
            { type: "attribution", term: "이기적 편향", desc: "성공은 내부귀인, 실패는 외부귀인으로 돌림" },
            { type: "relationship", term: "사회적 침투이론", desc: "주변부에서 중심부로 친교가 형성되는 과정" },
            { type: "relationship", term: "사회교환이론", desc: "비용과 보수의 상호교환으로 대인관계 설명" },
            { type: "group", term: "군중심리", desc: "군중 속에서 자기의식이 약화되는 현상" }
        ]
    }
];